name: Deploy to AWS EC2 with Apache Tomcat

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy WAR to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > ec2-key.pem
          chmod 400 ec2-key.pem
          scp -i ec2-key.pem target/your-springboot-app.war $EC2_USER@$EC2_HOST:/home/$EC2_USER/
          ssh -i ec2-key.pem $EC2_USER@$EC2_HOST <<EOF
            sudo mv /home/$EC2_USER/your-springboot-app.war /var/lib/tomcat/webapps/
            sudo systemctl restart tomcat
          EOF
